name: NoCheat

author: Evenprime

main: cc.co.evenprime.bukkit.nocheat.NoCheat
version: 1.06b

softdepend: [ Permissions, CraftIRC ]

commands:
  nocheat:
    description: Provides information about the current status of the NoCheat plugin
    usage: |
           /<command>
           Example: /<command> | Displays version, enabled checks and bugfixes
           Example: /<command> -p | Get your permissions, * = check disabled globally
           Example: /<command> -p [player] | Get permissions of the player, * = check disabled globally